//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnePassport.Takara.Android
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_close = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ctx_menu_add = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ctx_menu_delete = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int menu_add = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int menu_delete = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int treasurechest = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int treasurechestopen = 2130837511;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070004
			public const int BtnCancel = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int BtnOK = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int LvCategory = 2131165190;
			
			// aapt resource value: 0x7f07000a
			public const int LvTakaras = 2131165194;
			
			// aapt resource value: 0x7f070005
			public const int ScrollerView = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int ScrollerView2 = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int categoryDesc = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int categoryName = 2131165192;
			
			// aapt resource value: 0x7f070014
			public const int ctxMenuAdd = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int ctxMenuDelete = 2131165205;
			
			// aapt resource value: 0x7f070011
			public const int customTitle = 2131165201;
			
			// aapt resource value: 0x7f070000
			public const int icon = 2131165184;
			
			// aapt resource value: 0x7f070012
			public const int miAdd = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int miDelete = 2131165203;
			
			// aapt resource value: 0x7f070002
			public const int tCatDesc = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int tCatName = 2131165185;
			
			// aapt resource value: 0x7f07000b
			public const int takaraDesc = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int takaraName = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int tcoicon = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int tvDesc = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int tvName = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int tvValue = 2131165200;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddTakaraCategory = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int TakaraCategories = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int TakaraCategoriesLVR = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Takaras = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TakarasLVR = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int TakaraView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Titlebar = 2130903046;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int OptionsMenu = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int TakarasCtxMenu = 2131099649;
			
			private Menu()
			{
			}
		}
		
		public partial class Plurals
		{
			
			// aapt resource value: 0x7f050000
			public const int NoOfTakarasAvailable = 2131034112;
			
			private Plurals()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int CancelButton = 2130968580;
			
			// aapt resource value: 0x7f04000a
			public const int DeleteAlert = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int DeleteAlertNO = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int DeleteAlertYES = 2130968587;
			
			// aapt resource value: 0x7f040007
			public const int NewCat = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int OKButton = 2130968579;
			
			// aapt resource value: 0x7f040015
			public const int OptionsMenuItem1 = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int OptionsMenuItem2 = 2130968598;
			
			// aapt resource value: 0x7f040006
			public const int TVCatDesc = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int TVCatName = 2130968581;
			
			// aapt resource value: 0x7f040013
			public const int TakarasCtxMnuItem1 = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int TakarasCtxMnuItem2 = 2130968596;
			
			// aapt resource value: 0x7f040012
			public const int TakarasCtxMnuTitle = 2130968594;
			
			// aapt resource value: 0x7f04000d
			public const int TitleBar1_0 = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int TitleBar1_1 = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int TitleBar1_2 = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int TitleBar2_0 = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int TitleBarSeparator = 2130968593;
			
			// aapt resource value: 0x7f040000
			public const int TitleL1 = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int TitleL2 = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int TitleL3 = 2130968578;
			
			// aapt resource value: 0x7f040009
			public const int hint_catDesc = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int hint_catName = 2130968584;
			
			private String()
			{
			}
		}
	}
}
